// vue-version/javascript-version/full-version/src/views/pages/help-center/HelpCenterLandingKnowledgeBase.vue
<script setup>
const props = defineProps({
  categories: {
    type: Array,
    required: true,
  },
})

const totalArticles = category => {
  return category.subCategories.map(subCategory => subCategory.articles.length).reduce((partialSum, a) => partialSum + a, 0)
}
</script>

<template>
  <VRow>
    <VCol
      cols="12"
      lg="10"
      class="mx-auto mb-8"
    >
      <VRow class="match-height">
        <VCol
          v-for="article in props.categories"
          :key="article.title"
          cols="12"
          sm="6"
          md="4"
        >
          <VCard :title="article.title">
            <template #prepend>
              <VAvatar

                rounded
                size="34"
                :color="article.avatarColor"
                variant="tonal"
              >
                <VIcon
                  size="24"
                  :icon="article.icon"
                />
              </VAvatar>
            </template>

            <VCardText>
              <ul
                class="ps-6"
                style="list-style: disc ;"
              >
                <li
                  v-for="item in article.subCategories"
                  :key="item.title"
                  class="text-primary mb-2"
                >
                  <RouterLink
                    :to="{
                      name: 'pages-help-center-category-subcategory',
                      params: { category: article.slug, subcategory: item.slug },
                    }"
                  >
                    {{ item.title }}
                  </RouterLink>
                </li>
              </ul>

              <div class="mt-4">
                <RouterLink
                  :to="{
                    name: 'pages-help-center-category-subcategory',
                    params: { category: article.slug, subcategory: article.subCategories[0].slug },
                  }"
                  class="text-sm text-high-emphasis"
                >
                  {{ totalArticles(article) }} articles
                </RouterLink>
              </div>
            </VCardText>
          </VCard>
        </VCol>
      </VRow>
    </VCol>
  </VRow>
</template>

// react-version/typescript-version/full-version/src/views/pages/help-center/landing/HelpCenterLandingKnowledgeBase.tsx
// ** Next Import
import Link from 'next/link'

// ** MUI Imports
import Box from '@mui/material/Box'
import Grid from '@mui/material/Grid'
import Typography from '@mui/material/Typography'

// ** Icon Imports
import Icon from 'src/@core/components/icon'

// ** Custom Components Import
import CustomAvatar from 'src/@core/components/mui/avatar'

// ** Types
import { HelpCenterCategoriesType } from 'src/@fake-db/types'

const HelpCenterLandingKnowledgeBase = ({ categories }: { categories: HelpCenterCategoriesType[] }) => {
  const renderCategories = () => {
    if (categories && categories.length) {
      return categories.map(category => {
        const totalArticles = category.subCategories
          .map(subCategory => subCategory.articles.length)
          .reduce((partialSum, a) => partialSum + a, 0)

        return (
          <Grid item xs={12} sm={6} md={4} key={category.slug}>
            <Box
              sx={{
                p: 5,
                boxShadow: 6,
                height: '100%',
                display: 'flex',
                borderRadius: 1,
                flexDirection: 'column',
                alignItems: 'flex-start',
                backgroundColor: 'background.paper'
              }}
            >
              <Box sx={{ mb: 5, display: 'flex', alignItems: 'center' }}>
                <CustomAvatar
                  skin='light'
                  variant='rounded'
                  color={category.avatarColor}
                  sx={{ mr: 3, height: 34, width: 34 }}
                >
                  <Icon icon={category.icon} />
                </CustomAvatar>
                <Typography
                  variant='h6'
                  component={Link}
                  href={`/pages/help-center/${category.slug}/${category.subCategories[0].slug}`}
                  sx={{ fontWeight: 600, textDecoration: 'none', '&:hover': { color: 'primary.main' } }}
                >
                  {category.title}
                </Typography>
              </Box>
              <Box sx={{ mb: 5, display: 'flex', flexDirection: 'column', alignItems: 'flex-start' }}>
                {category.subCategories.map(subcategory => (
                  <Box
                    component={Link}
                    key={subcategory.title}
                    href={`/pages/help-center/${category.slug}/${subcategory.slug}`}
                    sx={{
                      display: 'flex',
                      alignItems: 'center',
                      textDecoration: 'none',
                      '&:not(:last-of-type)': { mb: 2 },
                      '& svg': { color: 'primary.main' }
                    }}
                  >
                    <Box sx={{ display: 'flex' }}>
                      <Icon icon='mdi:circle-small' />
                    </Box>
                    <Typography sx={{ color: 'primary.main' }}>{subcategory.title}</Typography>
                  </Box>
                ))}
              </Box>
              <Typography
                component={Link}
                href={`/pages/help-center/${category.slug}/${category.subCategories[0].slug}`}
                sx={{ mt: 'auto', textDecoration: 'none', '&:hover': { color: 'primary.main' } }}
              >
                {`${totalArticles} Articles`}
              </Typography>
            </Box>
          </Grid>
        )
      })
    } else {
      return null
    }
  }

  return (
    <Grid container spacing={6}>
      {renderCategories()}
    </Grid>
  )
}

export default HelpCenterLandingKnowledgeBase
