// vue-version/typescript-version/full-version/src/views/dashboard/crm/CrmMostSalesInCountries.vue
<script setup lang="ts">
const countrySales = [
  {
    sales: '18,879',
    title: 'Australia',
    trendNumber: -15,
  },
  {
    sales: '10,357',
    title: 'Canada',
    trendNumber: 85,
  },
  {
    sales: '4,860',
    title: 'India',
    trendNumber: 48,
  },
  {
    sales: '899',
    title: 'US',
    trendNumber: -16,
  },
  {
    sales: '43',
    title: 'Japan',
    trendNumber: 35,
  },
  {
    sales: '18',
    title: 'Brazil',
    trendNumber: 12,
  },
]

const moreList = [
  { title: 'Last 28 Days', value: 'Last 28 Days' },
  { title: 'Last Month', value: 'Last Month' },
  { title: 'Last Year', value: 'Last Year' },
]
</script>

<template>
  <VCard title="Most Sales in Countries">
    <template #append>
      <div class="me-n3 mt-n2">
        <MoreBtn :menu-list="moreList" />
      </div>
    </template>

    <VCardText>
      <div class="d-flex align-center mb-1">
        <h3 class="text-h3 font-weight-medium me-3">
          22,842
        </h3>

        <VChip
          text="+42%"
          size="x-small"
          color="success"
        />
      </div>

      <p class="text-xs mb-5">
        Sales Last 90 Days
      </p>

      <VDivider />

      <VTable>
        <tbody class="text-high-emphasis text-no-wrap">
          <tr
            v-for="sale in countrySales"
            :key="sale.title"
          >
            <td class="ps-0">
              {{ sale.title }}
            </td>

            <td class="text-end font-weight-semibold">
              {{ sale.sales }}
            </td>

            <td class="text-end font-weight-semibold pe-0">
              {{ Math.abs(sale.trendNumber) }}

              <VIcon
                :icon="Math.sign(sale.trendNumber) > 0 ? 'mdi-chevron-up' : 'mdi-chevron-down'"
                :color="Math.sign(sale.trendNumber) > 0 ? 'success' : 'error'"
                size="24"
              />
            </td>
          </tr>
        </tbody>
      </VTable>
    </VCardText>
  </VCard>
</template>

<style lang="scss" scoped>
.v-table--density-default > .v-table__wrapper > table > tbody > tr > td {
  block-size: 46px;
}
</style>

// react-version/typescript-version/full-version/src/views/dashboards/crm/CrmMostSalesInCountries.tsx
// ** React Imports
import { ReactNode } from 'react'

// ** MUI Imports
import Box from '@mui/material/Box'
import Card from '@mui/material/Card'
import Table from '@mui/material/Table'
import TableRow from '@mui/material/TableRow'
import TableBody from '@mui/material/TableBody'
import TableCell from '@mui/material/TableCell'
import Typography from '@mui/material/Typography'
import CardHeader from '@mui/material/CardHeader'
import CardContent from '@mui/material/CardContent'
import TableContainer from '@mui/material/TableContainer'

// ** Icon Imports
import Icon from 'src/@core/components/icon'

// ** Custom Components Imports
import CustomChip from 'src/@core/components/mui/chip'
import OptionsMenu from 'src/@core/components/option-menu'

interface DataType {
  title: string
  sales: string
  trend: ReactNode
  trendNumber: string
}

const data: DataType[] = [
  {
    sales: '18,879',
    title: 'Australia',
    trendNumber: '15%',
    trend: (
      <Box component='span' sx={{ display: 'flex', color: 'error.main' }}>
        <Icon icon='mdi:chevron-down' />
      </Box>
    )
  },
  {
    sales: '10,357',
    title: 'Canada',
    trendNumber: '85%',
    trend: (
      <Box component='span' sx={{ display: 'flex', color: 'success.main' }}>
        <Icon icon='mdi:chevron-up' />
      </Box>
    )
  },
  {
    sales: '4,860',
    title: 'India',
    trendNumber: '48%',
    trend: (
      <Box component='span' sx={{ display: 'flex', color: 'success.main' }}>
        <Icon icon='mdi:chevron-up' />
      </Box>
    )
  },
  {
    sales: '899',
    title: 'US',
    trendNumber: '16%',
    trend: (
      <Box component='span' sx={{ display: 'flex', color: 'error.main' }}>
        <Icon icon='mdi:chevron-down' />
      </Box>
    )
  },
  {
    sales: '43',
    title: 'Japan',
    trendNumber: '35%',
    trend: (
      <Box component='span' sx={{ display: 'flex', color: 'success.main' }}>
        <Icon icon='mdi:chevron-up' />
      </Box>
    )
  },
  {
    sales: '18',
    title: 'Brazil',
    trendNumber: '12%',
    trend: (
      <Box component='span' sx={{ display: 'flex', color: 'success.main' }}>
        <Icon icon='mdi:chevron-up' />
      </Box>
    )
  }
]

const CrmMostSalesInCountries = () => {
  return (
    <Card>
      <CardHeader
        title='Most Sales in Countries'
        titleTypographyProps={{ sx: { lineHeight: '2rem !important', letterSpacing: '0.15px !important' } }}
        action={
          <OptionsMenu
            options={['Last 28 Days', 'Last Month', 'Last Year']}
            iconButtonProps={{ size: 'small', className: 'card-more-options' }}
          />
        }
      />
      <CardContent sx={{ pb: theme => `${theme.spacing(1.75)} !important` }}>
        <Box sx={{ mb: 5, display: 'flex', flexDirection: 'column' }}>
          <Box sx={{ mb: 1.25, display: 'flex', alignItems: 'center' }}>
            <Typography variant='h3' sx={{ mr: 3.5 }}>
              22,842
            </Typography>
            <CustomChip
              skin='light'
              size='small'
              label='+42%'
              color='success'
              sx={{ height: 20, fontSize: '0.75rem', fontWeight: 500 }}
            />
          </Box>
          <Typography variant='caption'>Sales Last 90 Days</Typography>
        </Box>

        <TableContainer>
          <Table>
            <TableBody>
              {data.map((row: DataType) => {
                return (
                  <TableRow
                    key={row.title}
                    sx={{
                      '&:last-of-type td': { border: 0, pb: 0 },
                      '&:first-of-type td': { borderTop: theme => `1px solid ${theme.palette.divider}` },
                      '& .MuiTableCell-root': {
                        '&:last-of-type': { pr: 0 },
                        '&:first-of-type': { pl: 0 },
                        py: theme => `${theme.spacing(2.75)} !important`
                      }
                    }}
                  >
                    <TableCell>
                      <Box sx={{ display: 'flex', alignItems: 'center' }}>
                        <Typography sx={{ fontSize: '0.875rem' }}>{row.title}</Typography>
                      </Box>
                    </TableCell>
                    <TableCell align='right'>
                      <Typography sx={{ fontWeight: 600, fontSize: '0.875rem' }}>{row.sales}</Typography>
                    </TableCell>
                    <TableCell>
                      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
                        <Typography sx={{ mr: 1.5, fontWeight: 600, fontSize: '0.875rem' }}>
                          {row.trendNumber}
                        </Typography>
                        {row.trend}
                      </Box>
                    </TableCell>
                  </TableRow>
                )
              })}
            </TableBody>
          </Table>
        </TableContainer>
      </CardContent>
    </Card>
  )
}

export default CrmMostSalesInCountries
